### ISSUE TITLE
Cell barcode not being reported in counts file

### ISSUE THREAD

**Issue by dburkhardt** [CGATOxford/UMI-tools#278] opened 2018-09-24 19:57 UTC
Hello, 

I'm using UMI-tools to analyze single cell inDrops data downloaded from SRA. At the end of the pipeline, I'm getting a counts.txt file without cell barcodes. Instead, each 'cell' is assigned a number. I think I'm doing something wrong because the example output includes the actual cell barcode not a number.

Here's my current pipeline:

1. Align reads using STAR and manually add cell barcode and UMI from read name to `XC` and `XM` tags respectively.
2. Use featureCount to generate a bam file with `XT` tags for feature assignment
3. Use `umi-tools count` to generate a gene expression counts file.

Here's a snippet of the BAM output from featureCount:

```
SRR6890846.65463595#ATCTGCATC-GCTTACCT:GGAATG:NS500422_355_H3Y2TBGXY_4_23612_24407_15139_#length=33	0	1	33092	255	1S32M	*	0	0	CGCCCGTGCGACATCTGGTACATGCGCTTCTCC	AAAAAEEEEE/EEEEEEEEEEAEEEEEEEEEEE	NH:i:1	HI:i:1	AS:i:29	nM:i:1	NM:i:1	MD:Z:3A28	jM:B:c,-1	jI:B:i,-1	XC:Z:ATCTGCATC-GCTTACCT	XM:Z:GGAATG	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
SRR6890846.340526#TGACACAGTTT-TGGGATTC:TAGTGA:NS500422_345_H3VKVBGXY_1_11202_14587_17054_#length=33	0	1	33093	255	2S31M	*	0	0	CACCAGTGCGACATCTGGTACATGCGCTTCTCC	AAAAEEEEEE6AEEEEEEEEEEEEEEEAEEAEE	NH:i:1	HI:i:1	AS:i:30	nM:i:0	NM:i:0	MD:Z:31	jM:B:c,-1	jI:B:i,-1	XC:Z:TGACACAGTTT-TGGGATTC	XM:Z:TAGTGA	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
SRR6890846.14706139#TGATGTCTTTC-GCAGCATG:ACTACC:NS500422_345_H3VKVBGXY_3_23610_8531_17537_#length=33	0	1	33094	255	3S30M	*	0	0	CAACAGTGCGACATCTGGTACATGCGCTTCTCC	AAAAEEEEEEAEEEEAEEEEEEEEEE/EEEEEE	NH:i:1	HI:i:1	AS:i:29	nM:i:0	NM:i:0	MD:Z:30	jM:B:c,-1	jI:B:i,-1	XC:Z:TGATGTCTTTC-GCAGCATG	XM:Z:ACTACC	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
SRR6890846.40156007#GGATAAAG-TCCGTCCA:AGCCAG:NS500422_353_H52M2BGXY_4_21508_7246_6558_#length=34	0	1	33095	255	5S29M	*	0	0	ACAGTAGTGCGACATCTGGTACATGCGCTTCTCC	AAAAAEEEEAEEE/EEEEEEEEEEEE<AEEEEEE	NH:i:1	HI:i:1	AS:i:28	nM:i:0	NM:i:0	MD:Z:29	jM:B:c,-1	jI:B:i,-1	XC:Z:GGATAAAG-TCCGTCCA	XM:Z:AGCCAG	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
SRR6890846.47052001#ACGTGCTAG-CCCATCTG:CACTTT:NS500422_355_H3Y2TBGXY_1_23104_26396_18749_#length=32	0	1	33095	255	4S28M	*	0	0	AGTTAGTGCGACATCTGGTACATGCGCTTCTC	AAAEAEEEEEEEEE6EAAEEEEEEAEEEEAEE	NH:i:1	HI:i:1	AS:i:27	nM:i:0	NM:i:0	MD:Z:28	jM:B:c,-1	jI:B:i,-1	XC:Z:ACGTGCTAG-CCCATCTG	XM:Z:CACTTT	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
```

Note that cell-barcode tags look like `XC:Z:ACGTGCTAG-CCCATCTG` and UMI tags look like `XM:Z:CACTTT`.

I then use the following command to generate a `counts.txt` file:

`umi_tools count  --cell-tag-split=None --cell-tag-delimiter=- --per-gene --gene-tag=XT --umi-tag=XM --per-cell --cell-tag=XC -I test.bam -S count.txt`

And here's a head of the `count.txt` file.

```
gene	cell	count
ENSDARG00000001870	10803	1
ENSDARG00000001870	11212	1
ENSDARG00000001870	12230	1
ENSDARG00000001870	12325	1
ENSDARG00000001870	13454	1
ENSDARG00000001870	13907	1
ENSDARG00000001870	13970	1
ENSDARG00000001870	14109	1
ENSDARG00000001870	14610	1
```

See how the cell is reported with a number instead of a barcode? The single cell tutorial has led me to expect output in the following format:

```
gene	cell	count
ENSG00000000003	AAAGATGAGAAACGAG	3
ENSG00000000003	AACTCTTGTTCTGAAC	4
ENSG00000000003	ACACCGGGTACGACCC	2
ENSG00000000003	ACACTGAGTCGGGTCT	5
ENSG00000000003	ACTATCTCAAGGTGTG	2
ENSG00000000003	ACTGTCCCATATGGTC	11
ENSG00000000003	ACTGTCCTCATGCTCC	5
ENSG00000000003	AGAGCTTCACGACGAA	2
ENSG00000000003	AGCGGTCTCGATAGAA	2
```

I've tried playing with the `--cell-tag-split` and `--cell-tag-delimiter` functions to no avail.

Am I doing something wrong? Is there a parameter I'm missing?

Thanks!

**Comment by dburkhardt** [comment] 2018-09-24 19:57
Additionally, here's the output from the command:

```
# output generated by count --cell-tag-split=None --cell-tag-delimiter=- --per-gene --gene-tag=XT --umi-tag=XM --per-cell --cell-tag=XC -I test.sam -S /count.tsv
# job started at Mon Sep 24 15:52:53 2018 on orkney -- c37196f4-797d-4ef2-a040-e4ad0ad104d6
# pid: 34892, system: Linux 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64
# cell_tag                                : XC
# cell_tag_delim                          : -
# cell_tag_split                          : None
# chrom                                   : None
# compresslevel                           : 6
# gene_tag                                : XT
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# paired                                  : False
# per_cell                                : True
# per_contig                              : False
# per_gene                                : True
# random_seed                             : None
# short_help                              : None
# skip_regex                              : ^(__|Unassigned)
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/data/dan/sequencing/Klein_2018_wt_timecourse/test/4hpf.test.sam' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='/data/dan/sequencing/Klein_2018_wt_timecourse/test/4hpf.umi_count.tsv' mode='w' encoding='UTF-8'>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# umi_sep                                 : _
# umi_tag                                 : XM
# umi_tag_delim                           : None
# umi_tag_split                           : None
# wide_format_cell_counts                 : False
2018-09-24 15:52:55,575 INFO Input Reads: 99004
2018-09-24 15:52:55,576 INFO Read skipped, no tag: 23862
2018-09-24 15:52:55,576 INFO Number of reads counted: 65650
# job finished in 1 seconds at Mon Sep 24 15:52:55 2018 --  2.29  0.15  0.00  0.00 -- c37196f4-797d-4ef2-a040-e4ad0ad104d6
```

**Comment by TomSmithCGAT** [comment] 2018-09-25 11:45
Hi @dburkhardt - Thanks for detailing the issue so thoroughly and for providing the SAM. I'll look into this today and hopefully at least identify the cause

**Comment by dburkhardt** [comment] 2018-09-25 15:37
Thanks for the quick help @TomSmithCGAT . I have some more information that might reveal the issue. I tried running umi_tools on another dataset (also downloaded from SRA) that was sequenced using Drop-seq. I wanted to try this because the barcode sequence structure is different. Trying this, it appears that UMI-tools is looking for the cell-barcode and UMI information in the read name despite passing the `--cell-tag` and `--umi-tag` arguments. Is this the expected behavior? Could it be due to running python 3.7?

When I run:

`umi_tools count --per-gene --per-cell --gene-tag=XT --umi-tag=XM --cell-tag=XC --wide-format-cell-counts -I test2.bam -S counts.tsv`


I get the following output:

```
# output generated by count --per-gene --per-cell --gene-tag=XT --umi-tag=XM --cell-tag=XC --wide-format-cell-counts -I test2.bam -S counts.tsv
# job started at Tue Sep 25 11:24:36 2018 on orkney -- a48b4908-64db-4149-9592-d0fc7159c08c
# pid: 68907, system: Linux 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64
# cell_tag                                : XC
# cell_tag_delim                          : None
# cell_tag_split                          : -
# chrom                                   : None
# compresslevel                           : 6
# gene_tag                                : XT
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# paired                                  : False
# per_cell                                : True
# per_contig                              : False
# per_gene                                : True
# random_seed                             : None
# short_help                              : None
# skip_regex                              : ^(__|Unassigned)
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/home/dan/data/sequencing/Schier_2018_wt_timecourse/test/realigned/50epi_1.ZF50-DS2.test.bam.barcoded.bam.featureCounts.bam.sorted.bam' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='/home/dan/data/sequencing/Schier_2018_wt_timecourse/test/feature_counts/50epi_1-ZF50-DS2.counts.tsv' mode='w' encoding='UTF-8'>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# umi_sep                                 : _
# umi_tag                                 : XM
# umi_tag_delim                           : None
# umi_tag_split                           : None
# wide_format_cell_counts                 : True
Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 454, in get_barcode_read_id
    cell = read.qname.split(sep)[-2].encode('utf-8')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/.local/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/dan/.local/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/home/dan/.local/lib/python3.7/site-packages/umi_tools/count.py", line 110, in main
    for bundle, key, status in bundle_iterator(inreads):
  File "/home/dan/.local/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 1489, in __call__
    umi, cell = self.barcode_getter(read)
  File "/home/dan/.local/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 463, in get_barcode_read_id
    "Could not extract UMI +/- cell barcode from the read"
ValueError: Could not extract UMI +/- cell barcode from the readID, please check UMI is encoded in the read name
Traceback (most recent call last):
  File "generate_counts_matrix.py", line 104, in <module>
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
```

This looks to me like UMI-tools is looking for information in the qname when it's actually in the tags.


test2.bam looks like:

```
NB501164:203:H2WWMBGXY:1:21101:4714:5938#XC:CCCTCGGTTCGA#XM:GGCGTCAG	16	1	6365	255	4S46M	*	0	0	ACATCAGAACAGAACATTTAATGGAAATAGACTTAAGATGTCTGCGAGCC	A/AAAEEEEEEEEEEE<EEAEEEEAAAE<EEE<EEE<AEA<6<<<AAAAA	NH:i:1	HI:i:1	AS:i:37	nM:i:4	NM:i:4	MD:Z:2C1T11C2C26	jM:B:c,-1	jI:B:i,-1	XC:Z:CCCTCGGTTCGA	XM:Z:GGCGTCAG	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099104
NB501164:203:H2WWMBGXY:4:12512:5426:10467#XC:CCCTCGGTTCGA#XM:GGCGTCAG	16	1	6365	255	4S46M	*	0	0	ACATCAGAACAGAACATTTAATGGAAATAGACTTAAGATGTCTGCGAGCC	AAAAAAEAEEEEEEEEEEEEEEEEEAAAAEE/EEA/EEEE<EEEAA<E6A	NH:i:1	HI:i:1	AS:i:37	nM:i:4	NM:i:4	MD:Z:2C1T11C2C26	jM:B:c,-1	jI:B:i,-1	XC:Z:CCCTCGGTTCGA	XM:Z:GGCGTCAG	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099104
NB501164:203:H2WWMBGXY:3:22506:14588:15081#XC:TTAACGGTATGN#XM:GCTGACCA	16	1	6365	255	4S46M	*	0	0	TTTTCAGAACAGAACATTTAATGGAAATAGACTTAAGATGTCTGCGAGCC	/</E//AEEA<EEE/EE/EEEEEEEEEEEEEEAAEEEEEEEEEE/AAAAA	NH:i:1	HI:i:1	AS:i:37	nM:i:4	NM:i:4	MD:Z:2C1T11C2C26	jM:B:c,-1	jI:B:i,-1	XC:Z:TTAACGGTATGN	XM:Z:GCTGACCA	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099104
NB501164:229:H5TKTBGXY:2:11302:16232:11311#XC:TTAACGGTATGN#XM:GCTGACCA	16	1	6365	255	4S46M	*	0	0	TTTTCAGAACAGAACATTTAATGGAAATAGACTTAAGATGTCTGCGAGCC	/AA/AAEA<AEEEE<EEEAE<AEEEEEAEEEAEEEEEEEEEEEE/AAAAA	NH:i:1	HI:i:1	AS:i:37	nM:i:4	NM:i:4	MD:Z:2C1T11C2C26	jM:B:c,-1	jI:B:i,-1	XC:Z:TTAACGGTATGN	XM:Z:GCTGACCA	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099104
```

Here's a test2.bam:
https://drive.google.com/file/d/1LB9odcZHnFaTG1jekU-SjVqmlIRn1s3R/view?usp=sharing

So my current guess is that in my previous post, umi_tools was getting those number from the read name. Could this be a python3.7 bug? I'm not entirely sure how to run with python3.6, but if you give me a suggestion I'm happy to try it out.

**Comment by dhb2128** [comment] 2018-09-25 15:47
I think you need to call `umi_tools count` with `--extract-umi-method="tag"` since the default tries to extract the umi information from the read_id.

**Comment by TomSmithCGAT** [comment] 2018-09-25 16:33
Indeed! I'd hadn't spotted the missing parameter which needs to be given as shown above (thanks @dhb2128). Note that the quotation marks aren't necessary; adding `--extract-umi-method=tag` should solve your problems @dburkhardt .

**Comment by dburkhardt** [comment] 2018-09-25 18:58
Okay, thank you @dhb2128. I think this was the issue. I'm surprised this wasn't in the single cell tutorial or in the quick start guide. Is there another documentation page I should have read through? 

It would be nice if this was added to the documentation. I can make some edits and submit a PR if you like. 

It also would be nice to throw a warning if a user passes the `--umi-tag` or `--cell-barcode-tag` arguments but not the `--extract-umi-method` argument. Do these arguments have any other purpose? Why is the `--extract-umi-method` not set automatically by passing in the previous methods?

**Comment by TomSmithCGAT** [comment] 2018-09-25 21:17
Unfortunately, the options have been updated since the single cell tutorial and quick start page were produced. Hence the missing details. I agree it's not ideal if the user passes options which are not used and this is not raised as at least a warning. This is because the `--umi-tag` and `--cell-barcode-tag` options have default values so it's possible to deduplicate using the tags by just setting `--extract-umi-method=tag` if the default values are desired. The extract method defaults to read_id since this is the original implementation and we wanted to maintain backwards compatibility when introducing the tag-based deduplication.

On reflection, it would perhaps be better if the tag options were defaulted to None and the user required to explicitly specify the extract method to either read_id or tag, with warnings thrown when tag options were set but not `--extract-umi-method=tag`. Unfortunately, this will break any existing pipelines which use default values for any of these options. 

@IanSudbery, @dburkhardt, @dhb2128 - thoughts about the following resolutions?..

1. Set `--extract-umi-method`, `--umi-tag` and `--cell-barcode-tag` defaults to None. Throw an error if extract method not set and warning if tag(s) set but extract method != tag. To my mind, this is the most logical option if we were starting from scratch. However, this is not backwards compatible.
2. Keep `--extract-umi-method` defaulted to read_id. Set  `--umi-tag` and `--cell-barcode-tag` defaults to `None`. Throw a warning if tag(s) set but extract method != tag. Again, this is not backwards compatible but will only break pipelines using `--extract-umi-method=tag` and default tag values.
3. Keep `--extract-umi-method`, `--umi-tag` and `--cell-barcode-tag` defaulted to current values. If the user sets either tag option to non-default value, throw an warning if extract method is not set to tag. This will catch instances where a user wants to use the tags and has therefore set the tag values but not the extract method (as above). Is it possible in `argparse` to check whether a user has provided an option, regardless of what value was given, e.g even if it's the same as the default? If so, option 2 should capture all the reasonable cases. The only missed instance would be a user who wants to extract from the tags but does not provide values for either tag option (perhaps because the defaults are correct) and does not update the extract method. However, hopefully all users will be aware that additional parameters are required to extract from tags and this should not occur.

**Comment by TomSmithCGAT** [comment] 2018-09-26 06:59
Looks like option 3 above could be acheived by parsing `sys.argv` to check if `--umi-tag` or `--cell-barcode-tag` have been included on the command line regardless of what value was given. So an updated option 3 would be:

Keep `--extract-umi-method`, `--umi-tag` and `--cell-barcode-tag` defaulted to current values. If the user sets either tag option to *any* value, throw an warning if extract method is not set to tag. This will catch instances where a user wants to use the tags and has therefore set the tag values but not the extract method (as above). The only missed instance would be a user who wants to extract from the tags but does not provide values for either tag option (perhaps because the defaults are correct) and does not update the extract method. However, hopefully all users will be aware that additional parameters are required to extract from tags and this should not occur.

**Comment by IanSudbery** [comment] 2018-09-26 08:49
Yes my preference is for 3. In the long run we effectively deprecated `--extract-umi-method` in favour of just specifying `--umi-tag` and `--cell-barcode-tag` if you want their functionality, but we leave `--extract-umi-method` there for backwards compatibility. That might even allow the way for extracting one from a tag and the other from the read name.

**Comment by TomSmithCGAT** [comment] 2018-09-26 08:50
OK. I'll implement 3 in a branch now and include the update to the guides.

**Comment by TomSmithCGAT** [comment] 2018-09-26 10:17
@IanSudbery - Implemented in {TS}-DebugTagOptions branch. I've checked the behaviour is correct but it's not explicitly covered by any tests since I'm not sure how we would test for correct failing?

Checking over the quick start and single cell guide, we don't actually cover the options for extracting UMI/CB from BAM tags. `umi_tools dedup --help` includes the following which I think is sufficient along with the new error msg we're introducing:

```
--extract-umi-method (choice)
      How are the barcodes encoded in the read?

      Options are:

      - "read_id" (default)
            Barcodes are contained at the end of the read separated as
            specified with --umi-separator option

      - "tag"
            Barcodes contained in a tag(s), see --umi-tag/--cell-tag
            options

      - "umis"
            Barcodes were extracted using umis (https://github.com/vals/umis)

--umi-separator (string)
      Separator between read id and UMI. See --extract-umi-method above

--umi-tag (string)
      Tag which contains UMI. See --extract-umi-method above

--cell-tag (string)
      Tag which contains cell barcode. See --extract-umi-method above
```

Py2 tests are currently failing but once that's sorted we'd good to merge:
https://github.com/CGATOxford/UMI-tools/compare/ab81b657bf63...db281411aebe
https://travis-ci.org/CGATOxford/UMI-tools/builds/433394474

**Comment by IanSudbery** [comment] 2018-09-26 10:20
Looks good to me.

**Comment by TomSmithCGAT** [comment] 2018-09-26 11:13
OK, all done and merged into master #279

**Closed by TomSmithCGAT** 2018-09-26 11:13 UTC
Labels: Documentation, Next release, enhancement

**Comment by dburkhardt** [comment] 2018-09-26 15:43
Hey all, thanks for the quick help! My only advice here is that if there's a fork in the way UMI_tools works, it would be better to require the user to specify which of the forks they must take. _I.e._ I think option 1 is the safest in the long term. You could actually keep the defaults for the umi and barcode tags. Just setting the extract method to default `None` would fix this issue.

Here, the issue was that I didn't know there was a fork (to parse the read name or the tags), and I didn't know how to select between options. If I had tried running UMI-tools without passing `--extract-umi-method`, and the default was `None`, then I would have immediately known more about the structure of the program and how to interact with it. You could plan to make this change in the future by keeping a default method, but throwing a deprecation warning that in the future, the value will need to be specified. This will be a quick fix in the future to correct old scripts and shouldn't be a major break in backwards compatibility.

It also took a lot of guessing on my part to figure out which tags to set for the tag parsing to begin with. I think that it would be awesome to emphasize in some documentation exactly how the work flow of UMI tools works(my lab particularly like Readthedocs). I also think Bedtools does a great job with their illustrations of how the tool handles different user option (see their genomecov doc for one of my favorite examples https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html). 

I'm realizing this reads a little critical, but please know that I'm super impressed with all the work you've done so far, and I really think these methods are a needed advance in the field. I want to see these tools become widely used and easy-to-use so that it's adopted broadly. Thanks again for all of your hard work in this project.

**Comment by dburkhardt** [comment] 2018-09-26 18:44
Also, another note: it might be better to default `--cell-tag-split=None`. For the inDrops data I'm looking at the barcode string does include a dash. If I didn't know what the paramter did, the default of `--cell-tag-split=-` would silently split my barcodes without my intention. I think having a default to *not* split the barcode is better because 10X users should *explicitly* state that the `--cell-tag` is not truly a cell tag, but rather an amalgamation of two tags.

**Comment by TomSmithCGAT** [comment] 2018-09-26 21:01
Hi @dburkhardt. Don't worry about coming across as critical. As long as it's constructive it's all helpful! It's always useful to have opinions from users who are coming to UMI-tools in its current state since things have changed a lot since @IanSudbery's first implementation which was designed with iCLIP data in mind. We've tried to keep the tool set flexible and agnostic to the application but the more features one bolts on, the more inelegant these things become.

To be honest, as with many open source projects I imagine, UMI-tools is a (minor) side project for myself and Ian and we'd both like to have more time to improve many aspects of it. We've discussed readthedocs before and I agree this seems like a good route to improve the documentation which I think would help at lot, especially for first time users. Along with parallelisation and handling paired end reads more effectively, these are the long terms improvements that we would like to make if we had the time! 

I think bedtools is a great example of how to do these things well and I agree their documentation is exemplary. But take a look at their github page and they have 168 open issues and 17 open pull requests. Keeping on top of open source projects when they are no longer a major part of your research (bedtools was first developed in 2009) is really tough! Of course, if you want to help out with moving UMI-tools to readthedocs we'd be incredibly appreciative!

I'm inclined to agree with you regarding setting `--cell-tag-split` default to `None` but I think if we go down this route we would need to include a check for non-nucleotide values in the CB string. I'll have a think on this

**Comment by IanSudbery** [comment] 2018-09-27 12:49
So the reason for a lot of the defaults to make the whole pipeline as smooth as possible. If you start from fastq files and process using `umi_tools extract` and then deduplicate using `umi_tools dedup/group/count`, then the only option you should ever have to specify is `--bc-pattern` to `extract`, and perhaps `--per-cell` or `--per-gene` for single cell applications. 

The idea being that the average user should be able to run the pipeline through without worrying about the options, but still to provide flexibility to people who wish to do a less "off the shelf" analysis.
