### ISSUE TITLE
Is the TS-RefactorTools branch not ready yet?

### ISSUE THREAD

**Issue by peterch405** [CGATOxford/UMI-tools#21] opened 2016-04-05 17:00 UTC
I was opting to get the version that doesn't depend on CGAT, but simply running `umi_tools dedup --help` produces this error:

`Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 9, in <module>
    load_entry_point('umi-tools==0.0.1', 'console_scripts', 'umi_tools')()
  File "/usr/local/lib/python2.7/dist-packages/umi_tools-0.0.1-py2.7.egg/umi_tools/umi_tools.py", line 39, in main
    module = imp.load_module(command, file, pathname, description)
  File "/usr/local/lib/python2.7/dist-packages/umi_tools-0.0.1-py2.7.egg/umi_tools/dedup.py", line 182, in <module>
    from umi_tools._dedup_umi import edit_distance
ImportError: No module named _dedup_umi`

**Comment by IanSudbery** [comment] 2016-04-05 17:57
Hi peterch, 

The refactored branch is still undergoing testing. The problem is that the cython extension is not being isntalled in your site packages. A work around until we fix this is to install with:

```
$python setup.py develop
```

It will run the code from the clone repository and will be able to find the _umi_tools extension.

**Comment by TomSmithCGAT** [comment] 2016-04-06 21:42
Hi Peterch. The branch is not yet ready to merge into master but umi_tools should be available through  pip and conda now without the CGAT dependency. I've only tested the installation out under limited conditions but if you'd like to try it that would be very helpful. We're on our way to supporting python3 but currently only python >2.7 is supported.

If you use pip, you'll need to have pysam==0.8.4, cython and setuptools installed:

    pip install pysam==0.8.4
    pip install cython
    pip install setuptools
    pip install umi_tools==0.0.3

If you use conda, the following should work on linux and osx:

    conda install -c https://conda.anaconda.org/toms umi_tools

**Comment by TomSmithCGAT** [comment] 2016-05-10 16:56
This branch has now been merged with master

**Closed by TomSmithCGAT** 2016-05-10 16:56 UTC
