### ISSUE TITLE
Dubious grouping of barcodes through `UMIClusterer` API.

### ISSUE THREAD

**Issue by romanhaa** [CGATOxford/UMI-tools#355] opened 2019-07-22 21:07 UTC
Hi,

I'm using the `umi_tools.UMIClusterer()` API to group 18nt barcodes in some experiments through the following commands:

```python
import umi_tools
clusterer = umi_tools.UMIClusterer(cluster_method = 'directional')
barcodes_byte_format = [el.encode('UTF-8') for el in barcodes]
dict = dict(zip(barcodes_byte_format, barcode_counts))
clustered_barcodes = clusterer(dict, threshold = 2)
```

I tried different threshold between `2-5`. For a value of `2` I didn't notice anything strange, but as soon as I go above, already at `3`, I see that barcodes become grouped which have a Hamming distance larger than the set threshold. Here is an example:

```bash
TAGCAGCCACTCGACGCG # the barcode predicted to be correct
ACACTGACCCGCTGTTGG # one of the barcodes which will be corrected into the one above
---X-X-X-X-X-----X # X indicates matching nucleotides
```

Only 6 out of 18 nucleotides match in this pair.

Perhaps I misunderstood the method but I was under the assumption that the threshold was the only criteria based on which barcodes are grouped when using the `directional` method.

When increasing the threshold to `5` the connections between some barcodes become even less explainable to me.

```bash
TAGCAGCCACTCGACGCG # the barcode predicted to be correct with the degenerated ones below

...
TGCCTGAAAGCATCCTGG
AACCTAAATCAGGAGCGG
AATCCGGACGACACCACC
TGAACCTATAATCCTGTG
ACACGGATCAGCCTAGAG
ACACGATGACACACCCTA
AAAGCAGGCAACTCAATC
GGGGTAGCTAGTGGCGTT
ACATACCGAAATTACCAT
...
```

I'd be very happy if you could help me understand what's happening here.

Thanks :)

**Comment by IanSudbery** [comment] 2019-07-23 12:23
I am unable to reproduce the behavoit that you describe a above.
Specifically:
```
In [12]: barcodes

Out[12]:
{b'TAGCAGCCACTCGACGCG': 1,
 b'TGCCTGAAAGCATCCTGG': 1,
 b'AACCTAAATCAGGAGCGG': 1,
 b'AATCCGGACGACACCACC': 1,
 b'TGAACCTATAATCCTGTG': 1,
 b'ACACGGATCAGCCTAGAG': 1,
 b'ACACGATGACACACCCTA': 1,
 b'AAAGCAGGCAACTCAATC': 1,
 b'GGGGTAGCTAGTGGCGTT': 1,
 b'ACATACCGAAATTACCAT': 1}

In [13]: clusterer(barcodes, threshold=5)

Out[13]:
[[b'TAGCAGCCACTCGACGCG'],
 [b'TGCCTGAAAGCATCCTGG'],
 [b'AACCTAAATCAGGAGCGG'],
 [b'AATCCGGACGACACCACC'],
 [b'TGAACCTATAATCCTGTG'],
 [b'ACACGGATCAGCCTAGAG'],
 [b'ACACGATGACACACCCTA'],
 [b'AAAGCAGGCAACTCAATC'],
 [b'GGGGTAGCTAGTGGCGTT'],
 [b'ACATACCGAAATTACCAT']]
```
thus, each barcode is clustered into its own group. This is done using
`method='adjacency'`, which is like `directional`, but doesn't use counts,
since I don't have the counts that you used. So this is not quite a direct
replication but it should have been good enough. Are these 10 barcodes the
only barcodes going into the algorithm? If there are others, then these
sequences are probably being brought in transitively: that is, if barcode A
is within t edits of barcode B, and barcode B is within t edits of barcode
C, then C will be grouped with A (as long as the relative count criteria
are satisfied).

For this reason I'm not sure we'd ever recommend using a threshold of 5,
unless your barcodes were more like 100bp. In fact, our simulations suggest
that under normal error rates and duplication levels, you'd only need to go
up to an edit of 2 when your barcodes were more like 15-20. UMI-tools
relies on the fact that any barcode within the edit-ball is more likely to
be there due to an error than a coincidence. Its more likely that two
randomly selected 18nt barcodes are within 5nt of each than it is that one
arose as a sequencing/PCR error of the other, violating the basic
assumption we rely on .

That said, if you are getting barcodes 10nt different from each other
grouping together, without intermediate barcodes to connect them, then that
is a major bug that we need to sort.

**Comment by IanSudbery** [comment] 2019-07-23 12:25
I am unable to reproduce the behavoit that you describe a above.
Specifically:

```
In [12]: barcodes

Out[12]:
{b'TAGCAGCCACTCGACGCG': 1,
 b'TGCCTGAAAGCATCCTGG': 1,
 b'AACCTAAATCAGGAGCGG': 1,
 b'AATCCGGACGACACCACC': 1,
 b'TGAACCTATAATCCTGTG': 1,
 b'ACACGGATCAGCCTAGAG': 1,
 b'ACACGATGACACACCCTA': 1,
 b'AAAGCAGGCAACTCAATC': 1,
 b'GGGGTAGCTAGTGGCGTT': 1,
 b'ACATACCGAAATTACCAT': 1}

In [13]: clusterer(barcodes, threshold=5)

Out[13]:
[[b'TAGCAGCCACTCGACGCG'],
 [b'TGCCTGAAAGCATCCTGG'],
 [b'AACCTAAATCAGGAGCGG'],
 [b'AATCCGGACGACACCACC'],
 [b'TGAACCTATAATCCTGTG'],
 [b'ACACGGATCAGCCTAGAG'],
 [b'ACACGATGACACACCCTA'],
 [b'AAAGCAGGCAACTCAATC'],
 [b'GGGGTAGCTAGTGGCGTT'],
 [b'ACATACCGAAATTACCAT']]

```

thus, each barcode is clustered into its own group. This is done using
`method='adjacency'`, which is like `directional`, but doesn't use counts,
since I don't have the counts that you used. So this is not quite a direct
replication but it should have been good enough. Are these 10 barcodes the
only barcodes going into the algorithm? If there are others, then these
sequences are probably being brought in transitively: that is, if barcode A
is within t edits of barcode B, and barcode B is within t edits of barcode
C, then C will be grouped with A (as long as the relative count criteria
are satisfied).

For this reason I'm not sure we'd ever recommend using a threshold of 5,
unless your barcodes were more like 100bp. In fact, our simulations suggest
that under normal error rates and duplication levels, you'd only need to go
up to an edit of 2 when your barcodes were more like 15-20. UMI-tools
relies on the fact that any barcode within the edit-ball is more likely to
be there due to an error than a coincidence. Its more likely that two
randomly selected 18nt barcodes are within 5nt of each than it is that one
arose as a sequencing/PCR error of the other, violating the basic
assumption we rely on .

That said, if you are getting barcodes 10nt different from each other
grouping together, without intermediate barcodes to connect them, then that
is a major bug that we need to sort.

**Comment by TomSmithCGAT** [comment] 2020-07-07 14:07
I'm closing this due to low activity. Please re-open if this issue still needs to be resolved

**Closed by TomSmithCGAT** 2020-07-07 14:07 UTC
