### ISSUE TITLE
read names and barcode positions

### ISSUE THREAD

**Issue by nreid** [CGATOxford/UMI-tools#391] opened 2020-01-09 19:43 UTC
Hello, 

I've got 2 issues. 

1) I have paired end data, but the read names are not identical. R1 is appended with /1 and R2 with /2. This is causing the umi_tools extract to throw an error. Currently I'm working around it with a process substitution: <(zcat my.fq.gz | sed 's/..$//;n;n;n'), but it would be nice to not have to do this. We are starting to incorporate UMIs into RADseq data in population genetic studies, and a common tool for demultiplexing and QC of these data appends these /1 and /2 tags to the read names. 

2) The second problem is that my UMIs are on the 5' end of R2. 

if I run the following command:

umi_tools extract \
--bc-pattern2=NNNNNNNNNN \
-I test.1.fq.gz \
-S umi.1.fastq \
--read2-in=test.2.fq.gz \
--read2-out=umi.2.fastq

I get this error:

2020-01-09 14:18:16,839 INFO Starting barcode extraction
Traceback (most recent call last):
  File "/isg/shared/apps/umi_tools/1.0.0/bin/umi_tools", line 8, in <module>
    sys.exit(main())
  File "/isg/shared/apps/umi_tools/1.0.0/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/isg/shared/apps/umi_tools/1.0.0/lib/python3.6/site-packages/umi_tools/extract.py", line 407, in main
    reads = ReadExtractor(read1, read2)
  File "/isg/shared/apps/umi_tools/1.0.0/lib/python3.6/site-packages/umi_tools/extract_methods.py", line 487, in __call__
    umi_values = self.getBarcodes(read1, read2)
  File "/isg/shared/apps/umi_tools/1.0.0/lib/python3.6/site-packages/umi_tools/extract_methods.py", line 209, in _getBarcodesString
    umi_quals += umi_quals2
TypeError: must be str, not list

I've found that specifying --bc-pattern=XXXX solves the issue, but seems like I shouldn't have to do that, or at least it should be documented ( I didn't see it in the docs).

**Comment by IanSudbery** [comment] 2020-01-13 11:38
If your UMIs are on read2 rather than read1, then the easiest thing to do is to pass the read2 file to the read1 input and the read1 file to the read2 input thusL

```
umi_tools extract
--bc-pattern2=NNNNNNNNNN
-I test.2.fq.gz
-S umi.2.fastq
--read2-in=test.1.fq.gz
--read2-out=umi.1.fastq
```

I thought we had fixed the issue with /1 and /2 previously, but obviously not. I'll take a look.

**Comment by TomSmithCGAT** [comment] 2020-02-26 21:59
The appending of UMI (and optionally CB) to read name occurs here: https://github.com/CGATOxford/UMI-tools/blob/85d16746fbb72f9b4daa787ac67365b339485d61/umi_tools/extract_methods.py#L11-L24

I believe that the `/1`/`/2`would normally be appended to the read ids with whitespace in between (e.g http://seqanswers.com/forums/showthread.php?t=40015) which would be fine. However, even the wikipedia page for the fastq format shows an example without whitespace (https://en.wikipedia.org/wiki/FASTQ_format#Format). I'm slightly surprised this hasn't come up already!

It would be nice to check for this on the first n reads and then have alternative functions for adding the barcodes which are selected in `__int__`. The easier solution would be to check for `/1`/`/2` in every read but this would be very redundant

**Comment by TomSmithCGAT** [comment] 2020-03-02 21:46
Hi @nreid - I've added an option to `umi_tools extract` to deal with the trailing `\1`/`\2` (`--ignore-read-pair-suffixes). This is currently only available through the {ts}-ignore-read-pair-suffixes branch (https://github.com/CGATOxford/UMI-tools/tree/%7BTS%7D-ignore-read-pair-suffixes).

Would you mind testing that this works with you input fastqs without the need for passing them through `sed`

@IanSudbery - On the above branch,  `addBarcodesToIdentifier` is brough within `ExtractFilterAndUpdate` and becomes two methods `_addBarcodesToIdentifier` and `_addBarcodesToIdentifieIgnoreSuffix`, with the suitable method assigned to `self.addBarcodes` upon initiation of the `ReadExtractor` object. E.g the same way we end up handling most of the extract options. Assuming this options provides the intended behaviour, I'll add a test to cover this before PR.

**Comment by TomSmithCGAT** [comment] 2020-03-02 22:28
Ok, so going back through the backlog of issues, @IanSudbery was right. This problem was brought up a year ago, and resolved ... in a completely different manner! 🤦‍♂ 🤦‍♂ 🤦‍♂ 

Issue: #325, PR: #326

So, we now have two branches to resolve this issue:

1. #326 - adds an option to ignore read pair suffixes when checking the read IDs are the same. Also enables specification of non-default `\1` & `\2` suffixes. These options are passed as arguments to every call of `addBarcodesToIdentifier`
2. `{ts}-ignore-read-pair-suffixes`  - As described above, separates `addBarcodesToIdentifier` into two functions.

Option 1 is more flexible (though I'm not sure the suffixes are ever not `\1` or `\2`?) and makes a smaller change to the code base but at the cost of an additional `if` call with every read. Option 2 seems like the better option to me to avoid repeatedly checking if the suffixes should be ignored. We can always introduce the flexibility into option 2 if we desire later. I'll use the test files from #326 to add tests to `{ts}-ignore-read-pair-suffixes`

**Comment by TomSmithCGAT** [comment] 2020-09-14 19:47
This is now fixed in the master branch (see option `--ignore-read-pair-suffixes`) and will be available in the next release shortly

**Closed by TomSmithCGAT** 2020-09-14 19:47 UTC
