### ISSUE TITLE
Q: Inaccurate gene-level UMI counts? I do not think so.

### ISSUE THREAD

**Issue by reineckef** [CGATOxford/UMI-tools#197] opened 2017-10-14 08:31 UTC
Hello @IanSudbery,

I like your work, first of all. In your [Single_cell_tutorial](https://github.com/CGATOxford/UMI-tools/blob/master/doc/Single_cell_tutorial.md) you have a section that deals with post-processing a transcriptome-mapped STAR output. And I have a question around this:

> However, since we might encounter the same read twice (mapped to different transcripts of the
> same gene), UMI counts might be inaccurate.

If one read was written to many transcripts of the very same gene, its UMI will only be counted **once** for this gene. There should not be any inaccuracy of the UMI (not read!) count on the gene-level, correct? Transcript-level quantification is a different story, though.

Thank you very much!
Frank

**Comment by IanSudbery** [comment] 2017-10-14 08:38
Hi Frank,

The problem is not that the UMI  would be counted as rwo seperate UMIs,  rather that the count of that UMI will be inflated. Since we use the frequency with which each UMI appears not just the number of unique UMIs in the deduplication process,  that might lead to an inaccurate quantification.

**Comment by reineckef** [comment] 2017-10-14 08:55
Hi Ian,

Got it - I think. You say, a single UMI could be considered to be a valid founder (parent, I am not familiar with your wording here) population because it was seen many times, right? In fact, it should only considered to be a potential child/sibling/offspring. I have not thought about that. 

That is true unless you count unique read-id plus UMI combinations to get the real frequency of the UMI. The combination of read-id and UMI would still be found only once. But this will add dramatically to to the memory footprint and runtime, I guess.

Thanks for the swift reply! Keep up the good work.

Best,
Frank

**Closed** 2017-10-17 07:33 UTC
