### ISSUE TITLE
Dose umi tools support dealing insert and deletion in barcode?

### ISSUE THREAD

**Issue by yech1990** [CGATOxford/UMI-tools#64] opened 2016-12-08 15:04 UTC
I have design a long umi barcode 20xN. Due to primer synthesis error and sequencing error, the barcode may be 19bp or 21bp in length.  Dose UMI_tools take these situation into account?

**Comment by TomSmithCGAT** [comment] 2016-12-08 16:02
Hi @yech1990. Could you explain a little more how the UMI length varies? Unfortunately we can't cover all possible UMI encodings within umi_tools extract. However, if it's easy to detect within the read, it's usually straighforward to create a custom UMI extraction script since all we need to do is identify the UMI and append it to the read name (separated by '_'). See the top of the documentation for umi_tools dedup for clarification `umi_tools dedup --help`. I can share some code I've used for custom extraction if that would help?

P.s Thanks for the p3 compatibility pull request!

**Comment by yech1990** [comment] 2016-12-09 04:59
I do ultra-deep target sequencing, and the UMI barcode is added by PCR amplification.
The primer is in the form of  ```NNNNNNNNNNNNNNNNNNN--uniq primer for target---```
![image](https://cloud.githubusercontent.com/assets/5415510/21037970/18646808-be0d-11e6-9a29-31bea2a76dc8.png)

 I notice that ```umi_tools extract``` can only split barcode in a fix length and append it to the read name.
I can write a script to extract the barcode according to the target primer sequence. For the target primer is deterministic and the UMI is just on the left. 

If I pass these customize file to `umi_tools dedup`, how can the program deal with it, and wheather the directional model take these situation into account?

How to define 'distance' between these UMIs.
**ATGCATGC
ATGCAAGC
ATGCAGC
ATGCAATGC**

**Comment by TomSmithCGAT** [comment] 2016-12-09 10:42
Hi @yech1990. I didn't consider the implications of having different lengths properly. In the previous cases where the UMI position varied in the read, the length of the UMI was fixed so this was not an issue. We can't currently deal with UMIs which have different lengths so for now I'm afraid UMI-Tools will not be suitable. 

I guess we would need to use some form of alignment between UMIs to generate a 'distance' metric, e.g

ATGCATGC
ATGCA**A**GC
distance = 1

ATGCATGC
ATGCA-GC
distance = 1

ATGCA-TGC
ATGCAATGC
distance = 1

@IanSudbery Any thoughts?

**Comment by yech1990** [comment] 2016-12-09 10:56
distance metric will increase accuracy, but make the script much slower.

the I use 20bp UMI, and it will take one and a half day to group reads in one sample.

**Comment by TomSmithCGAT** [comment] 2016-12-09 11:25
@yech1990. Given that you're performing ultra-deep sequencing, I presume you have some positions with very high depth which makes the network building stage very time consuming. The time taken to build the network scales quadratically with the number of unique UMIs. Of course, aligning the UMIs rather than just calculating the edit distance will increase the time taken even more.

If your targeting sequencing involves more than one target, you can speed up the grouping/deduplication by aligning to the target genes/regions as separate contigs. You can then group/deduplicate each contig separately by providing the `--chrom` option and then merge together the results downstream.

**Comment by yech1990** [comment] 2016-12-09 13:01
@TomSmithCGAT  I split the data into different genes, but one sample file still contains millions of reads for each gene. 

I wonder whether the O(n²) is due to the low efficiency of the algorithm or python language. I tried some other code in github, which is much faster. 
I haven't read the code carefully,  what is the different between UMI_tools and those respiratory.
https://github.com/LaoZZZZZ/bartender-1.1

**Comment by TomSmithCGAT** [comment] 2016-12-09 13:24
@yech1990. We've used cython to speed up the edit distance calculation which is the function that gets called O(n²) times (I wrote a blog post about this [here](https://cgatoxford.wordpress.com/2016/02/01/speeding-up-python/)). Of course, this would be even faster in C++ etc. If anyone wants to re-implement our method in another language I'd be very happy to help out! However, ultimately, the problem is that we need to calculate the distance (edit or otherwise) between all pairs of unique UMIs which is O(n²), with respect to the number of unique UMIs and ~O(n) with respect to the length of the UMI. I'm not sure there's really any way around this except by performing some sort of prior filtering for which pairs of UMIs we want to calculate the distance between, say by only comparing low count UMIs to high count UMIs, but this would lead to sub-optimal solutions. 

I've not seen bartender previously but it appears that it doesn't handle UMI errors?
https://groups.google.com/forum/#!topic/bartenderrandombarcode/wbpIxLU6pbY
https://groups.google.com/forum/#!topic/bartenderrandombarcode/wbpIxLU6pbY

**Comment by IanSudbery** [comment] 2016-12-09 13:33
I was thinking that when we would only have to do an 'alignment' of the UMIs if they were different lengths. If you are sticking with a distance threshold of 1, then you would only have to test mutations or deletions - i.e. if two UMIs were different lengths, search or a deletion that would make a perfect match. If they are the same length look at mutations. Thus a comparison between two UMIs would still require the same number of string comparisons it does now. 

Alternatively, you could assume that the deletion always happens at oligo synthesis, and so UMIs of different lengths always belong in different networks. 

If someone were to go ahead with this they might want to run some tests to see if it was worth it, but I don't have time to do it ...

**Comment by yech1990** [comment] 2016-12-09 13:37
@TomSmithCGAT 
I notice this description in bartender readme

> -d: The maximum cluster distance that may be merged. The default value is 2. If the distance between two cluster sequences is within this threshold, these two sequences will be merged if they pass the statistical test set by the cluster merging threshold (z).

**Comment by yech1990** [comment] 2016-12-09 13:39
@IanSudbery 
sound reasonable.
Thank you very much

**Comment by IanSudbery** [comment] 2016-12-09 13:41
I just had a quick glance at Bartender:

What bartender does is cluster non-random sample barcodes using some sort of error correcting method. 

It will also allow the use of UMIs, but in a non-error correcting way similar to `--method=unique` in umi_tools. See this from their mailing list:

> Because it searches only for exact UMI matches, a PCR or sequencing error that happened to occur in a repeated UMI would not be recognized as a repeat and thus result in over-counting of that cluster.

**Comment by IanSudbery** [comment] 2016-12-09 13:43
@TomSmithCGAT: How much memory would a lookup table of all possible comparisons for a given UMI length take?

**Comment by TomSmithCGAT** [comment] 2016-12-09 14:10
For the fastest lookup, I guess we'd store all this as a np.array of bools. In which case we'd need (4^n)^2 elements or (5^n)^2 if we include Ns. 

          AAAA AAAT AAAC    ...     GGGG
AAAA    1        1        1        ...         0
AAAT    1        1        1         ...        0
AAAC    1        1        1        ...         0
...           0        1        0        ...         0
GGGG   0         0        0       ...          1 

I think this would be far too large unless UMI length was very small?

Alternatively, using a dictionary, with key = UMI, value=set of UMIs at edit_distance=1, we'd need 5^n keys each with a set of length n*5. 

{AAAA: set(AAAT, AAAC, AAAG, ...),
 AAAT: set(AAAA, AAAC, AAAG, ...),
... }

With a 12 bp UMI that would be >244M keys, each with a set containing 60 UMIs so this would still be unsuitable for large UMIs. 

Is there's a more compact way to store the lookup table?

**Comment by TomSmithCGAT** [comment] 2017-01-19 09:33
@yech1990 Are you OK if we close this issue?

**Closed** 2017-05-09 10:26 UTC
