### ISSUE TITLE
I/O operation on closed file 

### ISSUE THREAD

**Issue by bcantarel** [CGATOxford/UMI-tools#189] opened 2017-09-25 14:28 UTC
I am running umi_tools group using a bam file generated by BWA where I used blc2fastq to output the UMI into the readname

umi_tools group -I output.bam --method=unique --extract-umi-method=read_id --umi-separator=':' --umi-group-tag=MI --group-out=output.groups.tsv --output-bam -S output.grouped.bam

It appears that the output bam is complete, but here is an error that I am getting from the run.  Also, it looks like only one of the reads in the pair is getting the UMI tag.

Traceback (most recent call last):
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file Utilities.py, line 1072
Traceback (most recent call last):
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file Utilities.py, line 1072
Traceback (most recent call last):
  File "/project/shared/bicf_workflow_ref/seqprg/bin/umi_tools", line 9, in <module>
    load_entry_point('umi-tools==0.5.0', 'console_scripts', 'umi_tools')()
  File "/project/shared/bicf_workflow_ref/seqprg/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 50, in main
    module.main(sys.argv)
  File "/project/shared/bicf_workflow_ref/seqprg/lib/python2.7/site-packages/umi_tools/group.py", line 299, in main
    U.Stop()
  File "/project/shared/bicf_workflow_ref/seqprg/lib/python2.7/site-packages/umi_tools/Utilities.py", line 1019, in Stop
    global_options.stdlog.write(getFooter() + "\n")
ValueError: I/O operation on closed file

**Comment by IanSudbery** [comment] 2017-10-05 10:49
Thats strange. I'll have a look into it.

**Comment by IanSudbery** [comment] 2017-10-05 10:53
So only one of the reads getting the tag is by design. We are currently working on ways to add the tag to the other read. 

The error message you are getting is not something we have seen before and is puzzling. We will look into it.  However, all that is happening is that we are trying to write a time stamp for when the process finished to the log, which has been closed, so alll that is substantively missing is this one line of the log, the BAM should be fine.

**Comment by TomSmithCGAT** [comment] 2017-10-13 10:04
Hi @bcantarel - This is very odd behaviour. The error is essentially saying UMI-tools failed to write the final bit of the logfile. Since you haven't specified a file for the log, the logfile in this case is `stdout` so the error is saying that `stdout` is closed, which makes no sense to me. Could you try re-running but writing out the logging to a file (`-L group.log`) to see if the issue is specific to logging to `stdout`.

There's nothing wrong with your command. Just to make sure, I ran your exact command using python 2.7.13 and a test BAM file and couldn't reproduce the error. Could you also try running the following commands to download this test file and re-run your command
```
mkdir test_umi_tools; cd test_umi_tools
wget https://github.com/CGATOxford/UMI-tools/blob/master/tests/chr19_sep.bam
mv chr19_sep.bam output.bam
samtools index output.bam
umi_tools group -I output.bam --method=unique --extract-umi-method=read_id --umi-separator=':' --umi-group-tag=MI --group-out=output.groups.tsv --output-bam -S output.grouped.bam
```
If you installed directly from the GitHub repository, the above test file is in the repo @tests/chr19_sep.bam.

If you can process the test BAM OK but still get the error with your BAM, would you be able to subset your BAM to something manageable (say 1K reads), check you still get the error with the subsetted bam, and share the subset BAM with us? You can email it to me @: tss38@cam.ac.uk

**Comment by TomSmithCGAT** [comment] 2018-07-16 14:34
@bcantarel - I'm going to close this issue on the assumption that it has been resolved. Please re-open if this is not the case

**Closed by TomSmithCGAT** 2018-07-16 14:34 UTC
