### ISSUE TITLE
umi_tools whitelist barcode and umi only in the read2, but I found that  the barcode sequence not from the first base

### ISSUE THREAD

**Issue by Krascal** [CGATOxford/UMI-tools#296] opened 2018-11-07 18:16 UTC
In the data I analyzed, the paper said the barcode is the first 8 bps in read2, and the next 8 bps is the UMI, so the read1 didn't have the barcode/umi information. 
I used the instruction as below:
umi_tools whitelist -p=CCCCCCCCNNNNNNNN -L=test.exatract.log --stdin=test2.fastq > test.whitelist
but I found that the barcodes is not the first 8bps of read2, but is the 2-9th bp in read2, is this correct? And why?

**Comment by IanSudbery** [comment] 2018-11-07 18:52
You mean that you are asking UMI tools to use bases 1-8, but its actaully using bases 2-9? If thats the case, then this definately isn't right.

**Comment by TomSmithCGAT** [comment] 2018-11-16 17:04
Hi @Krascal - Can you clarify your question. Are you asking
1. "Is it reasonable that the UMI in read is contained in positions 2-9 rather than 1-8 as expected", or
2. "You gave `umi_tools` the command you state and it extracted positions 2-9 rather than 1-8 as you intended. Is this the expected output?"

If (1), this does seem odd but I guess it depends on the exact library preparation. If (2), as @IanSudbery says, this is not the expected behaviour. If you could include the first 4 lines of the inputs and output that would be great.

**Comment by TomSmithCGAT** [comment] 2019-01-16 16:14
@Krascal, I'm going to close this issue due to low activity. Please re-open if the issue has not been resolved

**Closed by TomSmithCGAT** 2019-01-16 16:14 UTC
